### ISSUE TITLE
Problems using BGZipWriter

### ISSUE THREAD

**Issue by hdetering** [xbrianh/bgzip#23]
Hi Brian, 
thanks for this module. I'd really like to use it but I'm having problems:
```{python}
(base) harry@T460p:~$ ipython
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import bgzip                                                                                                                   

In [2]: my_data = "this is a test."                                                                                                    

In [3]: with open("my_bgzipped_file.gz", "wb") as raw: 
   ...:   with bgzip.BGZipWriter(raw) as fh: 
   ...:     fh.write(my_data) 
   ...:                                                                                                                                
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-2d1dd6ace7cf> in <module>
      1 with open("my_bgzipped_file.gz", "wb") as raw:
      2   with bgzip.BGZipWriter(raw) as fh:
----> 3     fh.write(my_data)
      4 

~/.local/lib/python3.6/site-packages/bgzip/__init__.py in write(self, data)
    214 
    215     def write(self, data):
--> 216         self._input_buffer.extend(data)
    217         if len(self._input_buffer) > self.batch_size * bgzip_utils.block_data_inflated_size:
    218             self._compress()

TypeError: 'str' object cannot be interpreted as an integer
```

Does the data passed to `BGZipWriter.write()` need to be transformed to some sort of binary representation?

Cheers,
Harry

**Comment by xbrianh** [comment]
Hi Harry,

Yes, binary data is expected. The following snippet should work:
```
my_data = b"this is a test."  # Note the prefix "b"
with open("my_bgzipped_file.gz", "wb") as raw: 
    with bgzip.BGZipWriter(raw) as fh: 
        fh.write(my_data) 
```

There are a variety of ways to get binary data from text, e.g.
```
In [4]: normal_string = "this is a string"                                                                                    
In [5]: type(normal_string.encode("utf-8"))                                                                                   
Out[5]: bytes
```
It really depends on your use case.

**Comment by hdetering** [comment]
Thank you for the clarification and the usage examples!

I was trying to use BGZipWriter in tandem with [pyvcf](https://pyvcf.rtfd.org) (i.e. [vcf.Writer](https://pyvcf.readthedocs.io/en/latest/API.html#vcf-writer)), like so:
```
fn_vcf = 'input.vcf.gz'
fn_out = 'output.vcf.gz'
rdr = vcf.Reader(filename=fn_vcf)
if fn_out.endswith('.gz'):
      fh_out = open(fn_out, 'wb')
      fh = bgzip.BGZipWriter(fh_out)
wtr = vcf.Writer(fh, rdr)
```

Pyvcf internally uses the `write` method of the provided stream (here: `bgzip.BGZipWriter`) with a non-binary string, which then produces the error mentioned above:
```
  File "/mnt/netapp2/Home_FT2/home/uvi/be/hde/code/simtools/simtools/spikein.py", line 153, in write_vcfs
    wtr = vcf.Writer(fh, rdr)
  File "/home/uvi/be/hde/.local/lib/python3.7/site-packages/vcf/parser.py", line 666, in __init__
    stream.write('##{0}={1}\n'.format(key, val))
  File "/home/uvi/be/hde/.local/lib/python3.7/site-packages/bgzip/__init__.py", line 216, in write
    self._input_buffer.extend(data)
TypeError: 'str' object cannot be interpreted as an integer
```
(what else to expect from line `parser.py:666` :wink:)

It looks to me that the two modules probably don't play ball, do they? Do you know any way of putting a string-to-binary stream converter between `vcf.Writer` and `bgzip.BGZipWriter`?

If not, we can consider this issue "resolved".

Thanks again,
Harry

**Comment by hdetering** [comment]
After a while of tinkering with different custom IO stream classes I wasn't able to make `vcf.Writer` and `bgzip.BGZipWriter` work together.
A rather straightforward workaround, however, seems to be to check the input to `bgzip.BGZipWriter.write()` and convert it to `byte` if necessary.

**Comment by xbrianh** [comment]
If pyvcf wants to pass strings to `write`, the subclass shown below may work nicely.
```
from bgzip import BGZipWriter
  
class TXTBGZipWriter(BGZipWriter):
    def write(self, text):
        super().write(text.encode("utf-8"))

with open("my-text-file.txt.gz", "wb") as raw:
    with TXTBGZipWriter(raw) as fh:
        fh.write("this is my text")
```

**Comment by hdetering** [comment]
Hey, this works. Elegant solution, Brian! You might want to include it in the README / PyPI docs for others with similar use cases.
I'll withdraw my pull request, this way is fine without compromising your code.

Thanks again!
